### PR TITLE
Elm 0.19 upgrade (#3)

### LINKED ISSUE #3: Upgrade to Elm 0.19
Hi. Thanks for this package, keen to get it working (with Elm 0.19)! Not sure what the particular reasons are, but:

```bash
$ elm install Zinggi/elm-obj-loader
```
produces:
```
The following packages do not work with Elm 0.19.0 right now:

    Zinggi/elm-obj-loader
```

Would be happy to help (where I can, not an Elm *or* WebGL expert...)

### PR DESCRIPTION
**Pull request by declension**
Upgrade everything including dependencies for Elm 0.19

### Fix project / parser

 * Use `elm-upgrade` to _start_ this work (and convert the Elm JSON file)
 * Revert to using standard `array`
 * Use `andre-dietrich/parser-combinators` as a 0.19-compatible version of `Bogdanp/elm-combine`, and remove all usage thus of custom operators. It actually reads quite nicely I think.
 * `Debug.toString` where necessary, or `String.fromInt`
 * Convert n-tuples to records where n > 3 (the new maximum allowed)
 * Remove `Debug.crash`, as it's gone. Construct some useless data to satisfy the type-checker...
 * Sort out imports, the linter is stricter now...

###  Fix both examples for 0.19

 * Convert project to Elm 0.19
 * Use `Browser` not `Mouse` etc
 * Adjust some naming of `WebGL` imports
 * Rethink some tuples
 * Adjust `toString`s
 * use `Vec2` a bit more
 * Some Elm formatting (but not too much)
 * Catch more errors explicitly
 * Fix some name shadowing

This fixes #3

### CODE REVIEW

File: src/OBJ/Assembler.elm [hunk 1]
```diff
@@ -223,7 +219,22 @@ addFaceToMesh f mesh ({ vs, vts, vns, currentIndex } as state) =
 
         _ ->
             -- TODO: lift this error into a Result type
-            Debug.crash "mixed face types in the model!"
+            Debug.log "ERROR: mixed face types in the model!" <|
```
Comment (Zinggi) [inline src/OBJ/Assembler.elm]: If I recall correctly, we can't use any of the `Debug` functions in libraries or production builds.
So I think we probably just have to ignore the error.
Or lift this function into a `Result` type, but that will be more work.

File: src/OBJ/Assembler.elm [hunk 2]
```diff
@@ -223,7 +219,22 @@ addFaceToMesh f mesh ({ vs, vts, vns, currentIndex } as state) =
...
+
+            {      config = { withTangents=False }
```
Comment (Zinggi) [inline src/OBJ/Assembler.elm]: This isn't formatted by elm-format, right?
I assume you wanted to keep the diff clean (thanks for that), so you didn't run elm-format yet.
But I think it would also be fine if your last commit is actually just elm-format, since this also changed a bit since the 0.18 days.

File: src/OBJ/Parser.elm [hunk 3]
```diff
@@ -54,142 +63,164 @@ parseLine l =
 
 file : Parser s (List Line)
 file =
-    (many ignoredLines)
-        *> sepBy (many1 ignoredLines)
-            line
-        <* (many ignoredLines)
-        <* end
+    ignore (many ignoredLines) (sepBy (many1 ignoredLines) line)
```
Comment (Zinggi) [inline src/OBJ/Parser.elm:67]: I really like this, looks so much more readable :+1:

**Review by Zinggi — APPROVED** [review]
Amazing, absolutely tremendous work!
Thank you so much for your contribution!

I really like that you added useful tests. These will be of enormous help for possibly switching to another parser library or for performance improvements in the future.
Also, the `andAlso` trick is pretty neat, haven't seen this one before.

---
Given that you're very motivated and since you've put a lot of work into this, would you be interested in taking the lead? E.g. I could transfer the ownership of this repo to you. An alternative would be that you publish a fork and I link people to your fork in my readme. Interested?

File: src/OBJ/Assembler.elm (hunk 2 above)
Comment (declension) [reply src/OBJ/Assembler.elm]: Sure, done!

File: src/OBJ/Parser.elm (hunk 3 above)
Comment (declension) [reply src/OBJ/Parser.elm:67]: :smile:

File: src/OBJ/Assembler.elm (hunk 1 above)
Comment (declension) [reply src/OBJ/Assembler.elm]: Ah, yes :disappointed: 

>Or lift this function into a Result type, but that will be more work.

You're Not wrong there! I've been trying it for a couple of hours, the ripple effects are pretty huge (there are several places this needs fixing, resulting in a lot of functions that are lifted to `Result`. 

The problem is very few things have type annotations so it's inferred type errors only, and they're hard to read. So I tried adding them everywhere, but it's hard to see which errors are which now...
Does this look right?

```elm
type alias CompileState =
    {
    groups: Groups
    , currentGroupName: String
    , currentMaterialName : String
    , currentMesh : Maybe MeshT
    , currentGroup : Dict String Mesh
    , vs : Array Vec3
    , vts : Array Vec2
    , vns : Array Vec3
    , currentIndex : Int
    , knownVertexTextures : Dict Int3 Int
    , knownVertexTexturesTangents : Dict Int Int3
    , knownVertex : Dict Int2 Int
    , config : Settings
    }

emptyCompileState : Settings -> CompilerState
emptyCompileState config = ...
```

**Comment by declension** [comment]
> Given that you're very motivated and since you've put a lot of work into this, would you be interested in taking the lead? E.g. I could transfer the ownership of this repo to you. An alternative would be that you publish a fork and I link people to your fork in my readme. Interested?

Wow, thanks! That could be cool... though I'm not sure I know enough about 3D still though (or maybe even Elm, lol). Also, I'm doing it mainly for a work project, so there's an option that way too as I'm aiming to get us to become active in open-source (and maybe Elm). 

Can I get back to you on this perhaps?

File: examples/ElmLogo.elm [hunk 4]
```diff
@@ -254,14 +267,15 @@ subscriptions : Model -> Sub Msg
...
+            [ onMouseMove (decodeMouse MouseMove) ]
+
           else
             []
          )
-            ++ [ AnimationFrame.diffs Tick
-               , Mouse.downs MouseDown
-               , Mouse.ups (\_ -> MouseUp)
-               , Window.resizes ResizeWindow
+            ++ [ onAnimationFrame Tick
```
Comment (Zinggi) [inline examples/ElmLogo.elm]: I think you should be using [`onAnimationFrameDelta`](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Events#onAnimationFrameDelta) here

File: examples/ElmLogo.elm [hunk 5]
```diff
@@ -99,25 +92,33 @@ loadModel withTangents url =
...
+type alias CameraInfo =
+    { projection : Mat4, view : Mat4, viewProjection : Mat4, position : Vec3 }
+
+
 update : Msg -> Model -> ( Model, Cmd Msg )
 update msg model =
     case msg of
         Tick dt ->
-            ( { model | time = model.time + dt / 1000 }, Cmd.none )
+            ( { model | time = (posixToMillis dt |> toFloat) / 1000 }, Cmd.none )
```
Comment (Zinggi) [inline examples/ElmLogo.elm]: Once you switch to `onAnimationFrameDelta`, this no longer needs to use `posix` and the `model.time + ..` can be added back. In this example we only care about the total time, but in most animations and games we care about the delta time, so I'd prefer if this example also follows that

File: src/OBJ/Assembler.elm (hunk 1 above)
Comment (Zinggi) [reply src/OBJ/Assembler.elm]: Yeah, unfortunately I also gave up back then.. 
And I'm sorry, I can't really help you more here, I'm not familiar with the code anymore.

File: examples/ElmLogo.elm (hunk 5 above)
Comment (declension) [reply examples/ElmLogo.elm]: Ahh, right that explains it... thought that had been deprecated but must have missed it

File: src/OBJ/Assembler.elm (hunk 1 above)
Comment (declension) [reply src/OBJ/Assembler.elm]: OK. Perhaps I'll open that as a separate issue and leave it for now

**Comment by Zinggi** [comment]
> That could be cool... though I'm not sure I know enough about 3D still though (or maybe even Elm, lol). 

I had basically no idea about parsing, 3d file formats and 3d rendering before I created this. And I still know very little, there is just so much to learn.


> Also, I'm doing it mainly for a work project, so there's an option that way too as I'm aiming to get us to become active in open-source (and maybe Elm).

Cool, I love if a company supports open source!

I could merge this PR, but since I'm not really invested in this project anymore, I would prefer if you would publish the 0.19 version under your account (or your companies) account. How do you want to proceed?

**Comment by declension** [comment]
> I had basically no idea about parsing, 3d file formats and 3d rendering before I created this. And I still know very little, there is just so much to learn.

Cool, this gives me some hope maybe :grin: 

> I could merge this PR, but since I'm not really invested in this project anymore, I would prefer if you would publish the 0.19 version under your account (or your companies) account. How do you want to proceed?

OK great. I'm happy then if you'd still like to transfer the project over (I've never done this though...), and I can set up the publishing etc. If at work we end up using it a lot within the next few months then I'll look into more official ownership ideas (there are a few others repos I've been working on too perhaps), but I'll ask you again at that time :+1:

**Comment by Zinggi** [comment]
I tried to transfer the ownership of this repo to you, but since you have a fork under `declension/elm-obj-loader` the transfer failed. If you rename or remove that fork from github, I can transfer this repo to you.

**Comment by declension** [comment]
@Zinggi Thanks for that, I've now renamed it...

**Comment by Zinggi** [comment]
Apparently renaming is not enough, now I get "declension already has a repository in the Zinggi/elm-obj-loader network".
You might need to temporarily delete it, as ["The target account must not have a repository with the same name, or a fork in the same network"](https://help.github.com/en/articles/transferring-a-repository#about-repository-transfers)

**Comment by declension** [comment]
Ahh I see. I'm aware this PR might then get lost though...

**Comment by Zinggi** [comment]
Quite cumbersome, this transferring business... But I think it's best for this repo.

I think it's save to delete your fork now. I've included your branch in [this repo](https://github.com/Zinggi/elm-obj-loader/tree/feature/elm-0.19-upgrade) and once the transfer is complete all issues and PRs should be transferred as well.

**Comment by declension** [comment]
Ok, deleted! Hopefully that will unlock the magic...

**Comment by Zinggi** [comment]
Ok, I initiated the transfer, now you only need to accept

**Comment by declension** [comment]
Thanks!

**Comment by Zinggi** [comment]
Nice, it worked :tada: 

Thank you very much for your contribution and for taking over this project :clap: 

If you have any questions or want my feedback on a pull request, feel free to add me as a reviewer or ping me in a comment. You can also reach me on the elm slack (@zinggi57)
